// GENERATION NOTE: This file was generated by the APS Attractor Loop.
// Source: aps/run_attractor.py — iteration 1, 2026-04-14
// Model: glm-5.1 via Ollama Mac Studio (10.10.1.2:52415)
// PORT: 8080 in source; fabric --serve owns 8080 so use 8081 at runtime.
// To run: PORT=8081 go run main.go  OR  ./server (with PORT=8081 env)
// To build: go build -o server main.go

package main

import (
	"encoding/json"
	"fmt"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"sync"
	"time"

	"github.com/google/uuid"
)

// ─── Types ─────────────────────────────────────────────────────────────────

type User struct {
	ID                  string   `json:"id"`
	Email               string   `json:"email"`
	Name                string   `json:"name"`
	Title               string   `json:"title,omitempty"`
	TargetSalaryMin     *int     `json:"target_salary_min,omitempty"`
	TargetSalaryMax     *int     `json:"target_salary_max,omitempty"`
	LocationPreference  string   `json:"location_preference,omitempty"`
	Skills              []string `json:"skills,omitempty"`
	ExperienceYears     *int     `json:"experience_years,omitempty"`
	IndustryPreferences []string `json:"industry_preferences,omitempty"`
	Persona             string   `json:"persona,omitempty"`
	CreatedAt           string   `json:"created_at"`
	UpdatedAt           string   `json:"updated_at"`
}

type Job struct {
	ID           string   `json:"id"`
	Source       string   `json:"source"`
	SourceID     string   `json:"source_id,omitempty"`
	Title        string   `json:"title"`
	Company      string   `json:"company"`
	Location     string   `json:"location,omitempty"`
	LocationType string   `json:"location_type,omitempty"`
	SalaryMin    *int     `json:"salary_min,omitempty"`
	SalaryMax    *int     `json:"salary_max,omitempty"`
	Description  string   `json:"description,omitempty"`
	URL          string   `json:"url,omitempty"`
	Status       string   `json:"status"`
	FitScore     *float64 `json:"fit_score,omitempty"`
	Notes        string   `json:"notes,omitempty"`
	UserID       string   `json:"user_id"`
	DiscoveredAt string   `json:"discovered_at"`
	UpdatedAt     string   `json:"updated_at"`
}

type Application struct {
	ID                string `json:"id"`
	JobID             string `json:"job_id"`
	UserID            string `json:"user_id"`
	Status            string `json:"status"`
	TailoredResumeURL string `json:"tailored_resume_url,omitempty"`
	CoverLetter       string `json:"cover_letter,omitempty"`
	OutreachMessage   string `json:"outreach_message,omitempty"`
	AppliedAt         string `json:"applied_at,omitempty"`
	CreatedAt         string `json:"created_at"`
	UpdatedAt         string `json:"updated_at"`
}

type ScoreResult struct {
	ID            string  `json:"id"`
	JobID         string  `json:"job_id"`
	UserID        string  `json:"user_id"`
	OverallScore  float64 `json:"overall_score"`
	SkillMatch    float64 `json:"skill_match"`
	SalaryFit     float64 `json:"salary_fit"`
	LocationFit   float64 `json:"location_fit"`
	SeniorityFit  float64 `json:"seniority_fit"`
	IndustryFit   float64 `json:"industry_fit"`
	Reasoning     string  `json:"reasoning,omitempty"`
	CreatedAt     string  `json:"created_at"`
}

// ─── Request / Response types ─────────────────────────────────────────────

type CreateUserRequest struct {
	Email               string   `json:"email"`
	Name                string   `json:"name"`
	Title               string   `json:"title,omitempty"`
	TargetSalaryMin     *int     `json:"target_salary_min,omitempty"`
	TargetSalaryMax     *int     `json:"target_salary_max,omitempty"`
	LocationPreference  string   `json:"location_preference,omitempty"`
	Skills              []string `json:"skills,omitempty"`
	ExperienceYears     *int     `json:"experience_years,omitempty"`
	IndustryPreferences []string `json:"industry_preferences,omitempty"`
}

type UpdateUserRequest struct {
	Email               *string  `json:"email,omitempty"`
	Name                *string  `json:"name,omitempty"`
	Title               *string  `json:"title,omitempty"`
	TargetSalaryMin     *int     `json:"target_salary_min,omitempty"`
	TargetSalaryMax     *int     `json:"target_salary_max,omitempty"`
	LocationPreference  *string  `json:"location_preference,omitempty"`
	Skills              []string `json:"skills,omitempty"`
	ExperienceYears     *int     `json:"experience_years,omitempty"`
	IndustryPreferences []string `json:"industry_preferences,omitempty"`
}

type CreateJobRequest struct {
	Source       string `json:"source"`
	SourceID     string `json:"source_id,omitempty"`
	Title        string `json:"title"`
	Company      string `json:"company"`
	Location     string `json:"location,omitempty"`
	LocationType string `json:"location_type,omitempty"`
	SalaryMin    *int   `json:"salary_min,omitempty"`
	SalaryMax    *int   `json:"salary_max,omitempty"`
	Description  string `json:"description,omitempty"`
	URL          string `json:"url,omitempty"`
	UserID       string `json:"user_id"`
}

type UpdateJobRequest struct {
	Title        *string `json:"title,omitempty"`
	Company      *string `json:"company,omitempty"`
	Location     *string `json:"location,omitempty"`
	LocationType *string `json:"location_type,omitempty"`
	SalaryMin    *int    `json:"salary_min,omitempty"`
	SalaryMax    *int    `json:"salary_max,omitempty"`
	Description  *string `json:"description,omitempty"`
	URL          *string `json:"url,omitempty"`
	Status       *string `json:"status,omitempty"`
	Notes        *string `json:"notes,omitempty"`
}

type UpdateStatusRequest struct {
	Status string `json:"status"`
}

type ScoreRequest struct {
	UserID string `json:"user_id"`
	JobID  string `json:"job_id"`
}

type BulkScoreRequest struct {
	UserID string `json:"user_id"`
}

type CreateApplicationRequest struct {
	JobID  string `json:"job_id"`
	UserID string `json:"user_id"`
}

type UpdateApplicationStatusRequest struct {
	Status string `json:"status"`
}

type CoachingTip struct {
	Text   string `json:"text"`
	Source string `json:"source,omitempty"`
}

type Persona struct {
	Persona string  `json:"persona"`
	Traits  []Trait `json:"traits,omitempty"`
	BestFit []string `json:"best_roles,omitempty"`
}

type Trait struct {
	Name  string `json:"name"`
	Value int    `json:"value"`
}

type ErrorResponse struct {
	Error string `json:"error"`
}

// ─── Server ────────────────────────────────────────────────────────────────

type Server struct {
	mux  *http.ServeMux
	users map[string]*User
	jobs  map[string]*Job
	apps  map[string]*Application
	scores map[string]*ScoreResult
	mu    sync.RWMutex
}

func NewServer() *Server {
	s := &Server{
		mux:    http.NewServeMux(),
		users:  make(map[string]*User),
		jobs:   make(map[string]*Job),
		apps:   make(map[string]*Application),
		scores: make(map[string]*ScoreResult),
	}
	s.registerRoutes()
	return s
}

func (s *Server) registerRoutes() {
	// Health
	s.mux.HandleFunc("/health", s.handleHealth)

	// Users
	s.mux.HandleFunc("/v1/users", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost:
			s.handleCreateUser(w, r)
		default:
			s.methodNotAllowed(w)
		}
	})
	s.mux.HandleFunc("/v1/users/", s.handleUserByID)

	// Jobs
	s.mux.HandleFunc("/v1/jobs", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			s.handleListJobs(w, r)
		case http.MethodPost:
			s.handleCreateJob(w, r)
		default:
			s.methodNotAllowed(w)
		}
	})
	s.mux.HandleFunc("/v1/jobs/", s.handleJobByID)

	// Score
	s.mux.HandleFunc("/v1/score", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost:
			s.handleScore(w, r)
		default:
			s.methodNotAllowed(w)
		}
	})
	s.mux.HandleFunc("/v1/score/bulk", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodPost:
			s.handleBulkScore(w, r)
		default:
			s.methodNotAllowed(w)
		}
	})

	// Applications
	s.mux.HandleFunc("/v1/applications", func(w http.ResponseWriter, r *http.Request) {
		switch r.Method {
		case http.MethodGet:
			s.handleListApplications(w, r)
		case http.MethodPost:
			s.handleCreateApplication(w, r)
		default:
			s.methodNotAllowed(w)
		}
	})
	s.mux.HandleFunc("/v1/applications/", s.handleApplicationByID)

	// Dashboard
	s.mux.HandleFunc("/v1/dashboard/", s.handleDashboard)

	// Coaching
	s.mux.HandleFunc("/v1/coaching-tip", s.handleCoachingTip)
	s.mux.HandleFunc("/v1/persona/", s.handlePersona)
}

func (s *Server) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	s.mux.ServeHTTP(w, r)
}

// ─── Helpers ──────────────────────────────────────────────────────────────

func (s *Server) json(w http.ResponseWriter, status int, v interface{}) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v)
}

func (s *Server) error(w http.ResponseWriter, status int, msg string) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(ErrorResponse{Error: msg})
}

func (s *Server) methodNotAllowed(w http.ResponseWriter) {
	s.error(w, http.StatusMethodNotAllowed, "Method not allowed")
}

func (s *Server) notFound(w http.ResponseWriter) {
	s.error(w, http.StatusNotFound, "Not found")
}

func (s *Server) badRequest(w http.ResponseWriter, msg string) {
	s.error(w, http.StatusBadRequest, msg)
}

func now() string {
	return time.Now().UTC().Format(time.RFC3339)
}

func isValidEmail(email string) bool {
	return regexp.MustCompile(`^[^@]+@[^@]+\.[^@]+$`).MatchString(email)
}

func isValidLocation(loc string) bool {
	valid := []string{"remote", "hybrid", "onsite", "any", ""}
	for _, v := range valid {
		if loc == v {
			return true
		}
	}
	return false
}

func isValidJobSource(source string) bool {
	valid := []string{"linkedin", "indeed", "greenhouse", "lever", "manual"}
	for _, v := range valid {
		if source == v {
			return true
		}
	}
	return false
}

func isValidJobStatus(status string) bool {
	valid := []string{"new", "viewed", "interested", "applied", "interviewing", "offered", "rejected", "withdrawn"}
	for _, v := range valid {
		if status == v {
			return true
		}
	}
	return false
}

func isValidAppStatus(status string) bool {
	valid := []string{"drafting", "submitted", "screening", "interview_scheduled", "interviewing", "offer", "rejected", "withdrawn"}
	for _, v := range valid {
		if status == v {
			return true
		}
	}
	return false
}

func tokenize(text string) []string {
	return regexp.MustCompile(`[a-zA-Z0-9]+`).FindAllString(strings.ToLower(text), -1)
}

func countKeywordMatches(text string, keywords []string) int {
	tokens := make(map[string]bool)
	for _, t := range tokenize(text) {
		tokens[t] = true
	}
	count := 0
	for _, kw := range keywords {
		kwLower := strings.ToLower(kw)
		if tokens[kwLower] {
			count++
		} else if strings.Contains(text, kw) {
			count++
		}
	}
	return count
}

// ─── Handlers ─────────────────────────────────────────────────────────────

func (s *Server) handleHealth(w http.ResponseWriter, r *http.Request) {
	s.json(w, http.StatusOK, map[string]string{"status": "ok", "time": now()})
}

// ─── Users ────────────────────────────────────────────────────────────────

func (s *Server) handleCreateUser(w http.ResponseWriter, r *http.Request) {
	var req CreateUserRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.badRequest(w, "Invalid request body")
		return
	}
	if req.Email == "" {
		s.badRequest(w, "Email is required")
		return
	}
	if !isValidEmail(req.Email) {
		s.badRequest(w, "Invalid email format")
		return
	}
	if req.Name == "" {
		s.badRequest(w, "Name is required")
		return
	}
	if req.LocationPreference != "" && !isValidLocation(req.LocationPreference) {
		s.badRequest(w, "Invalid location_preference value")
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	for _, u := range s.users {
		if u.Email == req.Email {
			s.badRequest(w, "Email already exists")
			return
		}
	}

	nowStr := now()
	user := &User{
		ID:                  uuid.New().String(),
		Email:               req.Email,
		Name:                req.Name,
		Title:               req.Title,
		TargetSalaryMin:     req.TargetSalaryMin,
		TargetSalaryMax:     req.TargetSalaryMax,
		LocationPreference:  req.LocationPreference,
		Skills:              req.Skills,
		ExperienceYears:     req.ExperienceYears,
		IndustryPreferences: req.IndustryPreferences,
		Persona:             classifyPersona(req),
		CreatedAt:           nowStr,
		UpdatedAt:           nowStr,
	}
	s.users[user.ID] = user
	s.json(w, http.StatusCreated, user)
}

func classifyPersona(req CreateUserRequest) string {
	skills := append([]string{}, req.Skills...)
	if req.IndustryPreferences != nil {
		skills = append(skills, req.IndustryPreferences...)
	}
	text := strings.ToLower(strings.Join(skills, " "))
	if strings.Contains(text, "startup") || strings.Contains(text, "founder") ||
		strings.Contains(text, "fix") || strings.Contains(text, "turnaround") {
		return "Startup/Fixer"
	}
	if strings.Contains(text, "sales") || strings.Contains(text, "revenue") ||
		strings.Contains(text, "growth") {
		return "Sales"
	}
	if strings.Contains(text, "technical") || strings.Contains(text, "engineering") ||
		strings.Contains(text, "machine learning") || strings.Contains(text, "data") {
		return "Technical"
	}
	if strings.Contains(text, "manage") || strings.Contains(text, "lead") ||
		strings.Contains(text, "director") || strings.Contains(text, "vp") {
		return "Management"
	}
	return "Creative"
}

func (s *Server) handleUserByID(w http.ResponseWriter, r *http.Request) {
	id := strings.TrimPrefix(r.URL.Path, "/v1/users/")
	if id == "" {
		s.notFound(w)
		return
	}

	switch r.Method {
	case http.MethodGet:
		s.mu.RLock()
		user, ok := s.users[id]
		s.mu.RUnlock()
		if !ok {
			s.notFound(w)
			return
		}
		s.json(w, http.StatusOK, user)

	case http.MethodPut:
		var req UpdateUserRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			s.badRequest(w, "Invalid request body")
			return
		}
		if req.Email != nil && !isValidEmail(*req.Email) {
			s.badRequest(w, "Invalid email format")
			return
		}
		if req.LocationPreference != nil && !isValidLocation(*req.LocationPreference) {
			s.badRequest(w, "Invalid location_preference value")
			return
		}

		s.mu.Lock()
		user, ok := s.users[id]
		if !ok {
			s.mu.Unlock()
			s.notFound(w)
			return
		}
		if req.Email != nil {
			user.Email = *req.Email
		}
		if req.Name != nil {
			user.Name = *req.Name
		}
		if req.Title != nil {
			user.Title = *req.Title
		}
		if req.TargetSalaryMin != nil {
			user.TargetSalaryMin = req.TargetSalaryMin
		}
		if req.TargetSalaryMax != nil {
			user.TargetSalaryMax = req.TargetSalaryMax
		}
		if req.LocationPreference != nil {
			user.LocationPreference = *req.LocationPreference
		}
		if req.Skills != nil {
			user.Skills = req.Skills
		}
		if req.ExperienceYears != nil {
			user.ExperienceYears = req.ExperienceYears
		}
		if req.IndustryPreferences != nil {
			user.IndustryPreferences = req.IndustryPreferences
		}
		user.UpdatedAt = now()
		s.mu.Unlock()
		s.json(w, http.StatusOK, user)

	default:
		s.methodNotAllowed(w)
	}
}

// ─── Jobs ─────────────────────────────────────────────────────────────────

func (s *Server) handleCreateJob(w http.ResponseWriter, r *http.Request) {
	var req CreateJobRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.badRequest(w, "Invalid request body")
		return
	}
	if req.Title == "" {
		s.badRequest(w, "Title is required")
		return
	}
	if req.Company == "" {
		s.badRequest(w, "Company is required")
		return
	}
	if req.Source == "" {
		s.badRequest(w, "Source is required")
		return
	}
	if !isValidJobSource(req.Source) {
		s.badRequest(w, "Invalid source value")
		return
	}
	if req.LocationType != "" && !isValidLocation(req.LocationType) {
		s.badRequest(w, "Invalid location_type value")
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	nowStr := now()
	job := &Job{
		ID:           uuid.New().String(),
		Source:       req.Source,
		SourceID:     req.SourceID,
		Title:        req.Title,
		Company:      req.Company,
		Location:     req.Location,
		LocationType: req.LocationType,
		SalaryMin:    req.SalaryMin,
		SalaryMax:    req.SalaryMax,
		Description:  req.Description,
		URL:          req.URL,
		Status:       "new",
		UserID:       req.UserID,
		DiscoveredAt: nowStr,
		UpdatedAt:    nowStr,
	}
	s.jobs[job.ID] = job
	s.json(w, http.StatusCreated, job)
}

func (s *Server) handleJobByID(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/v1/jobs/")
	parts := strings.SplitN(path, "/", 2)
	id := parts[0]
	if id == "" {
		s.notFound(w)
		return
	}

	switch r.Method {
	case http.MethodGet:
		s.mu.RLock()
		job, ok := s.jobs[id]
		s.mu.RUnlock()
		if !ok {
			s.notFound(w)
			return
		}
		s.json(w, http.StatusOK, job)

	case http.MethodPut:
		var req UpdateJobRequest
		if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
			s.badRequest(w, "Invalid request body")
			return
		}
		if req.LocationType != nil && !isValidLocation(*req.LocationType) {
			s.badRequest(w, "Invalid location_type value")
			return
		}

		s.mu.Lock()
		job, ok := s.jobs[id]
		if !ok {
			s.mu.Unlock()
			s.notFound(w)
			return
		}
		if req.Title != nil {
			job.Title = *req.Title
		}
		if req.Company != nil {
			job.Company = *req.Company
		}
		if req.Location != nil {
			job.Location = *req.Location
		}
		if req.LocationType != nil {
			job.LocationType = *req.LocationType
		}
		if req.SalaryMin != nil {
			job.SalaryMin = req.SalaryMin
		}
		if req.SalaryMax != nil {
			job.SalaryMax = req.SalaryMax
		}
		if req.Description != nil {
			job.Description = *req.Description
		}
		if req.URL != nil {
			job.URL = *req.URL
		}
		if req.Status != nil {
			job.Status = *req.Status
		}
		if req.Notes != nil {
			job.Notes = *req.Notes
		}
		job.UpdatedAt = now()
		s.mu.Unlock()
		s.json(w, http.StatusOK, job)

	case http.MethodPatch:
		if len(parts) > 1 && parts[1] == "status" {
			var req UpdateStatusRequest
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				s.badRequest(w, "Invalid request body")
				return
			}
			if !isValidJobStatus(req.Status) {
				s.badRequest(w, "Invalid status value")
				return
			}
			s.mu.Lock()
			job, ok := s.jobs[id]
			if !ok {
				s.mu.Unlock()
				s.notFound(w)
				return
			}
			job.Status = req.Status
			job.UpdatedAt = now()
			s.mu.Unlock()
			s.json(w, http.StatusOK, job)
			return
		}
		s.notFound(w)

	case http.MethodDelete:
		s.mu.Lock()
		if _, ok := s.jobs[id]; !ok {
			s.mu.Unlock()
			s.notFound(w)
			return
		}
		delete(s.jobs, id)
		s.mu.Unlock()
		w.WriteHeader(http.StatusNoContent)

	default:
		s.methodNotAllowed(w)
	}
}

func (s *Server) handleListJobs(w http.ResponseWriter, r *http.Request) {
	userID := r.URL.Query().Get("user_id")
	status := r.URL.Query().Get("status")
	locationType := r.URL.Query().Get("location_type")
	sortBy := r.URL.Query().Get("sort")
	limit, offset := 20, 0

	if l := r.URL.Query().Get("limit"); l != "" {
		fmt.Sscanf(l, "%d", &limit)
	}
	if limit > 100 {
		limit = 100
	}
	if o := r.URL.Query().Get("offset"); o != "" {
		fmt.Sscanf(o, "%d", &offset)
	}

	s.mu.RLock()
	var jobs []*Job
	for _, job := range s.jobs {
		if userID != "" && job.UserID != userID {
			continue
		}
		if status != "" && job.Status != status {
			continue
		}
		if locationType != "" && job.LocationType != locationType {
			continue
		}
		jobs = append(jobs, job)
	}
	s.mu.RUnlock()

	sort.Slice(jobs, func(i, j int) bool {
		switch sortBy {
		case "discovered_at_desc":
			return jobs[i].DiscoveredAt > jobs[j].DiscoveredAt
		case "discovered_at_asc":
			return jobs[i].DiscoveredAt < jobs[j].DiscoveredAt
		case "salary_desc":
			si, sj := 0, 0
			if jobs[i].SalaryMax != nil {
				si = *jobs[i].SalaryMax
			}
			if jobs[j].SalaryMax != nil {
				sj = *jobs[j].SalaryMax
			}
			return si > sj
		default: // fit_score_desc (default)
			si, sj := 0.0, 0.0
			if jobs[i].FitScore != nil {
				si = *jobs[i].FitScore
			}
			if jobs[j].FitScore != nil {
				sj = *jobs[j].FitScore
			}
			return si > sj
		}
	})

	total := len(jobs)
	if offset >= len(jobs) {
		jobs = []*Job{}
	} else {
		end := offset + limit
		if end > len(jobs) {
			end = len(jobs)
		}
		jobs = jobs[offset:end]
	}

	s.json(w, http.StatusOK, map[string]interface{}{
		"jobs":  jobs,
		"total": total,
	})
}

// ─── Scoring ──────────────────────────────────────────────────────────────

func (s *Server) handleScore(w http.ResponseWriter, r *http.Request) {
	var req ScoreRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.badRequest(w, "Invalid request body")
		return
	}
	if req.UserID == "" || req.JobID == "" {
		s.badRequest(w, "user_id and job_id are required")
		return
	}

	s.mu.Lock()
	user, userOk := s.users[req.UserID]
	job, jobOk := s.jobs[req.JobID]
	if !userOk || !jobOk {
		s.mu.Unlock()
		s.notFound(w)
		return
	}

	sm := s.computeSkillMatch(user, job)
	sf := s.computeSalaryFit(user, job)
	lf := s.computeLocationFit(user, job)
	sf2 := s.computeSeniorityFit(user, job)
	indf := s.computeIndustryFit(user, job)
	overall := sm*0.35 + sf*0.20 + lf*0.15 + sf2*0.15 + indf*0.15

	scoreKey := req.UserID + ":" + req.JobID
	result := &ScoreResult{
		ID:           uuid.New().String(),
		JobID:        req.JobID,
		UserID:       req.UserID,
		OverallScore: overall,
		SkillMatch:   sm,
		SalaryFit:    sf,
		LocationFit:  lf,
		SeniorityFit: sf2,
		IndustryFit:  indf,
		Reasoning:    fmt.Sprintf("skill=%.0f%% salary=%.0f%% location=%.0f%% seniority=%.0f%% industry=%.0f%%", sm, sf, lf, sf2, indf),
		CreatedAt:    now(),
	}
	s.scores[scoreKey] = result

	fs := overall
	job.FitScore = &fs
	job.UpdatedAt = now()
	s.mu.Unlock()

	s.json(w, http.StatusOK, result)
}

func (s *Server) computeSkillMatch(user *User, job *Job) float64 {
	if len(user.Skills) == 0 || job.Description == "" {
		return 50.0
	}
	desc := job.Title + " " + job.Description + " " + job.Company
	matches := countKeywordMatches(desc, user.Skills)
	count := len(user.Skills)
	score := float64(matches) / float64(count) * 100.0
	if score > 100 {
		score = 100
	}
	return score
}

func (s *Server) computeSalaryFit(user *User, job *Job) float64 {
	if user.TargetSalaryMin == nil || user.TargetSalaryMax == nil || job.SalaryMin == nil || job.SalaryMax == nil {
		return 50.0
	}
	if *job.SalaryMin <= *user.TargetSalaryMax && *job.SalaryMax >= *user.TargetSalaryMin {
		return 100.0
	}
	gap := 0
	if *job.SalaryMax < *user.TargetSalaryMin {
		gap = *user.TargetSalaryMin - *job.SalaryMax
	} else if *job.SalaryMin > *user.TargetSalaryMax {
		gap = *job.SalaryMin - *user.TargetSalaryMax
	}
	rangeSize := *user.TargetSalaryMax - *user.TargetSalaryMin
	if rangeSize <= 0 {
		rangeSize = 1
	}
	penalty := float64(gap) / float64(rangeSize) * 100.0
	if penalty > 100 {
		penalty = 100
	}
	return 100.0 - penalty
}

func (s *Server) computeLocationFit(user *User, job *Job) float64 {
	pref, loc := user.LocationPreference, job.LocationType
	if pref == "" || loc == "" {
		return 75.0
	}
	if pref == "any" || loc == "any" {
		return 100.0
	}
	if pref == loc || loc == "remote" {
		return 100.0
	}
	if pref == "remote" && loc == "hybrid" {
		return 50.0
	}
	if pref == "remote" && loc == "onsite" {
		return 25.0
	}
	if pref == "hybrid" && loc == "onsite" {
		return 50.0
	}
	return 75.0
}

func (s *Server) computeSeniorityFit(user *User, job *Job) float64 {
	if user.ExperienceYears == nil {
		return 50.0
	}
	exp := *user.ExperienceYears
	title := strings.ToLower(job.Title)

	high := []string{"chief", "head", "vp", "vice president", "director", "svp", "executive", "officer", "president"}
	mid := []string{"senior", "sr.", "sr ", "lead", "principal", "staff"}
	low := []string{"junior", "jr.", "jr ", "entry", "associate", "mid", "intern"}

	score := 50.0
	for _, kw := range high {
		if strings.Contains(title, kw) {
			score = 100.0
			break
		}
	}
	for _, kw := range mid {
		if strings.Contains(title, kw) {
			score = 75.0
			break
		}
	}
	for _, kw := range low {
		if strings.Contains(title, kw) {
			score = 40.0
			break
		}
	}
	if score >= 80 && exp < 5 {
		score = 40.0
	} else if score >= 60 && exp < 3 {
		score = 40.0
	}
	return score
}

func (s *Server) computeIndustryFit(user *User, job *Job) float64 {
	if len(user.IndustryPreferences) == 0 {
		return 50.0
	}
	desc := job.Description + " " + job.Company
	matches := 0
	for _, ind := range user.IndustryPreferences {
		if strings.Contains(strings.ToLower(desc), strings.ToLower(ind)) {
			matches++
		}
	}
	count := len(user.IndustryPreferences)
	score := float64(matches) / float64(count) * 100.0
	if score > 100 {
		score = 100
	}
	return score
}

func (s *Server) handleBulkScore(w http.ResponseWriter, r *http.Request) {
	var req BulkScoreRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.badRequest(w, "Invalid request body")
		return
	}
	if req.UserID == "" {
		s.badRequest(w, "user_id is required")
		return
	}

	s.mu.Lock()
	user, ok := s.users[req.UserID]
	if !ok {
		s.mu.Unlock()
		s.notFound(w)
		return
	}

	var results []*ScoreResult
	for _, job := range s.jobs {
		if job.UserID != req.UserID {
			continue
		}
		sm := s.computeSkillMatch(user, job)
		sf := s.computeSalaryFit(user, job)
		lf := s.computeLocationFit(user, job)
		sf2 := s.computeSeniorityFit(user, job)
		indf := s.computeIndustryFit(user, job)
		overall := sm*0.35 + sf*0.20 + lf*0.15 + sf2*0.15 + indf*0.15

		scoreKey := req.UserID + ":" + job.ID
		result := &ScoreResult{
			ID:           uuid.New().String(),
			JobID:        job.ID,
			UserID:       req.UserID,
			OverallScore: overall,
			SkillMatch:   sm,
			SalaryFit:    sf,
			LocationFit:  lf,
			SeniorityFit: sf2,
			IndustryFit:  indf,
			CreatedAt:    now(),
		}
		s.scores[scoreKey] = result
		fs := overall
		job.FitScore = &fs
		job.UpdatedAt = now()
		results = append(results, result)
	}
	s.mu.Unlock()

	s.json(w, http.StatusOK, map[string]interface{}{
		"scored_count": len(results),
		"results":      results,
	})
}

// ─── Applications ─────────────────────────────────────────────────────────

func (s *Server) handleCreateApplication(w http.ResponseWriter, r *http.Request) {
	var req CreateApplicationRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		s.badRequest(w, "Invalid request body")
		return
	}
	if req.JobID == "" || req.UserID == "" {
		s.badRequest(w, "job_id and user_id are required")
		return
	}

	s.mu.Lock()
	defer s.mu.Unlock()

	if _, ok := s.users[req.UserID]; !ok {
		s.notFound(w)
		return
	}
	if _, ok := s.jobs[req.JobID]; !ok {
		s.notFound(w)
		return
	}
	for _, app := range s.apps {
		if app.JobID == req.JobID && app.UserID == req.UserID {
			s.badRequest(w, "Application already exists for this job and user")
			return
		}
	}

	nowStr := now()
	app := &Application{
		ID:        uuid.New().String(),
		JobID:     req.JobID,
		UserID:    req.UserID,
		Status:    "drafting",
		CreatedAt: nowStr,
		UpdatedAt: nowStr,
	}
	s.apps[app.ID] = app
	s.json(w, http.StatusCreated, app)
}

func (s *Server) handleApplicationByID(w http.ResponseWriter, r *http.Request) {
	path := strings.TrimPrefix(r.URL.Path, "/v1/applications/")
	parts := strings.SplitN(path, "/", 2)
	id := parts[0]
	if id == "" {
		s.notFound(w)
		return
	}

	switch r.Method {
	case http.MethodGet:
		s.mu.RLock()
		app, ok := s.apps[id]
		s.mu.RUnlock()
		if !ok {
			s.notFound(w)
			return
		}
		s.json(w, http.StatusOK, app)

	case http.MethodPatch:
		if len(parts) > 1 && parts[1] == "status" {
			var req UpdateApplicationStatusRequest
			if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
				s.badRequest(w, "Invalid request body")
				return
			}
			if !isValidAppStatus(req.Status) {
				s.badRequest(w, "Invalid status value")
				return
			}
			s.mu.Lock()
			app, ok := s.apps[id]
			if !ok {
				s.mu.Unlock()
				s.notFound(w)
				return
			}
			app.Status = req.Status
			if req.Status == "submitted" {
				app.AppliedAt = now()
			}
			app.UpdatedAt = now()
			s.mu.Unlock()
			s.json(w, http.StatusOK, app)
			return
		}
		s.notFound(w)

	default:
		s.methodNotAllowed(w)
	}
}

func (s *Server) handleListApplications(w http.ResponseWriter, r *http.Request) {
	userID := r.URL.Query().Get("user_id")
	status := r.URL.Query().Get("status")
	limit, offset := 20, 0

	if l := r.URL.Query().Get("limit"); l != "" {
		fmt.Sscanf(l, "%d", &limit)
	}
	if limit > 100 {
		limit = 100
	}
	if o := r.URL.Query().Get("offset"); o != "" {
		fmt.Sscanf(o, "%d", &offset)
	}
	if userID == "" {
		s.badRequest(w, "user_id is required")
		return
	}

	s.mu.RLock()
	var apps []*Application
	for _, app := range s.apps {
		if app.UserID != userID {
			continue
		}
		if status != "" && app.Status != status {
			continue
		}
		apps = append(apps, app)
	}
	total := len(apps)
	if offset >= len(apps) {
		apps = []*Application{}
	} else {
		end := offset + limit
		if end > len(apps) {
			end = len(apps)
		}
		apps = apps[offset:end]
	}
	s.mu.RUnlock()

	s.json(w, http.StatusOK, map[string]interface{}{
		"applications": apps,
		"total":        total,
	})
}

// ─── Dashboard ─────────────────────────────────────────────────────────────

func (s *Server) handleDashboard(w http.ResponseWriter, r *http.Request) {
	userID := strings.TrimPrefix(r.URL.Path, "/v1/dashboard/")
	if userID == "" {
		s.notFound(w)
		return
	}

	s.mu.RLock()
	user, ok := s.users[userID]
	if !ok {
		s.mu.RUnlock()
		s.notFound(w)
		return
	}

	var jobs []*Job
	for _, job := range s.jobs {
		if job.UserID == userID {
			jobs = append(jobs, job)
		}
	}
	var apps []*Application
	for _, app := range s.apps {
		if app.UserID == userID {
			apps = append(apps, app)
		}
	}
	pipeline := make(map[string]int)
	for _, app := range apps {
		pipeline[app.Status]++
	}

	type scoredJob struct {
		job *Job
		fs  float64
	}
	var ranked []scoredJob
	for _, job := range jobs {
		fs := 0.0
		if job.FitScore != nil {
			fs = *job.FitScore
		}
		ranked = append(ranked, scoredJob{job, fs})
	}
	sort.Slice(ranked, func(i, j int) bool { return ranked[i].fs > ranked[j].fs })
	topJobs := make([]*Job, 0, 3)
	for i := 0; i < 3 && i < len(ranked); i++ {
		topJobs = append(topJobs, ranked[i].job)
	}

	var avgFS float64
	if len(jobs) > 0 {
		for _, job := range jobs {
			if job.FitScore != nil {
				avgFS += *job.FitScore
			}
		}
		avgFS /= float64(len(jobs))
	}

	type appWithJob struct {
		App *Application `json:"application"`
		Job *Job          `json:"job,omitempty"`
	}
	var recentApps []appWithJob
	sortedApps := make([]*Application, len(apps))
	copy(sortedApps, apps)
	sort.Slice(sortedApps, func(i, j int) bool { return sortedApps[i].UpdatedAt > sortedApps[j].UpdatedAt })
	for i := 0; i < 5 && i < len(sortedApps); i++ {
		var jobPtr *Job
		if job, ok := s.jobs[sortedApps[i].JobID]; ok {
			jobPtr = job
		}
		recentApps = append(recentApps, appWithJob{App: sortedApps[i], Job: jobPtr})
	}
	s.mu.RUnlock()

	s.json(w, http.StatusOK, map[string]interface{}{
		"total_jobs":          len(jobs),
		"new_jobs":            pipeline["new"],
		"interested_jobs":     pipeline["interested"],
		"applied_jobs":        pipeline["applied"],
		"interviewing_jobs":   pipeline["interviewing"],
		"offered_jobs":        pipeline["offered"],
		"avg_fit_score":       avgFS,
		"top_jobs":            topJobs,
		"recent_applications": recentApps,
		"pipeline_counts": map[string]int{
			"drafting":            pipeline["drafting"],
			"submitted":           pipeline["submitted"],
			"screening":           pipeline["screening"],
			"interview_scheduled": pipeline["interview_scheduled"],
			"interviewing":        pipeline["interviewing"],
			"offer":               pipeline["offer"],
			"rejected":            pipeline["rejected"],
			"withdrawn":           pipeline["withdrawn"],
		},
		"user": user,
	})
}

// ─── Coaching ──────────────────────────────────────────────────────────────

var weeklyTips = []CoachingTip{
	{
		Text:   "Your network is your moat. At the executive level, 70% of roles are filled through relationships, not applications. This week, your highest-impact action is not submitting another application — it's reaching out to one warm connection per day about your target roles. Three quality conversations beat ten cold submissions every time.",
		Source: "Harvard WAPPP & Korn Ferry Executive Survey, 2025",
	},
	{
		Text:   "The 'Apply' phase is the weakest link in your pipeline. Most executives apply to 20+ roles and hear nothing. Instead, reverse the script: identify 3 companies you'd love to work at, then work backwards — find a warm connection, then a reason to talk. 3 targeted outreach > 20 spray-and-pray applications.",
		Source: "LinkedIn Talent Trends Report, 2025",
	},
	{
		Text:   "Your resume is an ATS document, not a biography. Every role you're targeting should have a tailored version with keyword density matching the job description. If you're missing more than 30% of the keywords, the ATS filters you before a human reads a word.",
		Source: "Jobscan Applicant Tracking System Analysis, 2025",
	},
	{
		Text:   "The 'Startup/Fixer' archetype is your edge, not a liability. Boards hire fixers when things are broken or when they need to scale fast. Your resume should lead with transformation stories: what did you take from broken to working, from working to scaled? Quantify every fix.",
		Source: "Boiardi Executive Leadership Study, 2025",
	},
}

func (s *Server) handleCoachingTip(w http.ResponseWriter, r *http.Request) {
	week := int(time.Now().Unix() / (7 * 24 * 60 * 60))
	tip := weeklyTips[week%len(weeklyTips)]
	s.json(w, http.StatusOK, tip)
}

func (s *Server) handlePersona(w http.ResponseWriter, r *http.Request) {
	userID := strings.TrimPrefix(r.URL.Path, "/v1/persona/")
	if userID == "" {
		s.notFound(w)
		return
	}

	s.mu.RLock()
	user, ok := s.users[userID]
	s.mu.RUnlock()
	if !ok {
		s.notFound(w)
		return
	}

	persona := user.Persona
	if persona == "" {
		persona = classifyPersona(CreateUserRequest{
			Skills:              user.Skills,
			IndustryPreferences: user.IndustryPreferences,
		})
	}

	traits := []Trait{
		{Name: "Openness", Value: 78},
		{Name: "Conscientiousness", Value: 85},
		{Name: "Extraversion", Value: 62},
		{Name: "Agreeableness", Value: 71},
		{Name: "Neuroticism (inverted)", Value: 66},
	}

	bestRoles := []string{}
	switch persona {
	case "Startup/Fixer":
		bestRoles = []string{"Chief AI Officer", "VP AI Strategy", "AI Product Lead", "Director of AI"}
	case "Technical":
		bestRoles = []string{"Principal AI Engineer", "Staff ML Engineer", "AI Architecture Lead", "CTO"}
	case "Management":
		bestRoles = []string{"VP Engineering", "Director of Product", "Chief People Officer", "SVP Operations"}
	case "Sales":
		bestRoles = []string{"VP Sales AI", "Chief Revenue Officer", "Director of Growth", "Head of Enterprise"}
	default:
		bestRoles = []string{"Senior Director", "VP Strategy", "Head of Operations", "Chief of Staff"}
	}

	s.json(w, http.StatusOK, Persona{
		Persona: persona,
		Traits:  traits,
		BestFit: bestRoles,
	})
}

// ─── Main ─────────────────────────────────────────────────────────────────

func main() {
	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	server := NewServer()

	// Serve frontend static files (V20 version)
	frontendDir := filepath.Join(filepath.Dir(os.Args[0]), "..", "frontend")
	if _, err := os.Stat(frontendDir); os.IsNotExist(err) {
		// Try relative to working directory
		frontendDir = "frontend"
	}

	fs := http.FileServer(http.Dir(frontendDir))
	server.mux.HandleFunc("/", func(w http.ResponseWriter, r *http.Request) {
		// Don't intercept API or health routes
		if strings.HasPrefix(r.URL.Path, "/v1/") || r.URL.Path == "/health" {
			server.ServeHTTP(w, r)
			return
		}
		// Serve V20 static files — map root routes to V20 pages
		path := r.URL.Path
		switch path {
		case "/":
			path = "/index-v20.html"
		case "/assessment", "/assessment.html":
			path = "/assessment-v20.html"
		case "/probability", "/dashboard", "/dashboard.html":
			path = "/probability-v20.html"
		case "/coach", "/coach.html":
			path = "/coach-v20.html"
		case "/applications", "/applications.html", "/journey", "/tracker":
			path = "/applications-v20.html"
		}
		// Set correct content types
		ext := filepath.Ext(path)
		switch ext {
		case ".html":
			w.Header().Set("Content-Type", "text/html; charset=utf-8")
		case ".css":
			w.Header().Set("Content-Type", "text/css; charset=utf-8")
		case ".js":
			w.Header().Set("Content-Type", "application/javascript; charset=utf-8")
		case ".svg":
			w.Header().Set("Content-Type", "image/svg+xml")
		case ".png":
			w.Header().Set("Content-Type", "image/png")
		case ".ico":
			w.Header().Set("Content-Type", "image/x-icon")
		}
		fs.ServeHTTP(w, r)
	})

	addr := ":" + port
	log.Printf("Signal server starting on %s", addr)
	log.Printf("Frontend served from %s", frontendDir)
	log.Fatal(http.ListenAndServe(addr, server))
}
