#!/usr/bin/env node
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/**
 * Generates src/version.ts from package.json at build time.
 * Single source of truth: package.json → version.ts → tsc → dist/
 */

import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const SDK_DIR = resolve(import.meta.dir, "..");
const pkg = JSON.parse(readFileSync(resolve(SDK_DIR, "package.json"), "utf8"));

const content = `// Auto-generated by scripts/inject-version.ts — do not edit.
export const SDK_VERSION = '${pkg.version}';
`;

writeFileSync(resolve(SDK_DIR, "src/version.ts"), content);
console.log(`✅ Injected SDK_VERSION = '${pkg.version}' → src/version.ts`);
